### ISSUE TITLE
Распознавание изображений - new

### ISSUE THREAD

**Issue by plahov** [TalismanFR/gigachat-php-sdk#2]
Планируются дополнение новыми возможностями, такими как работа с файлами ([Распознавание изображений](https://developers.sber.ru/docs/ru/gigachat/api/working-with-files))?

**Comment by TalismanFR** [comment]
Доброго дня! Да, новые функционал с распознованием, а так же обработка файлов генерируемых в ответах. Сейчас в процессе функционал хранилища файлов `/files`.

**Comment by plahov** [comment]
Отлично, очень жду). Спасибо за проект.

**Comment by TalismanFR** [comment]
Реализовано.
