### ISSUE TITLE
Кеширование запросов

### ISSUE THREAD

**Issue by plahov** [TalismanFR/gigachat-php-sdk#3]
Добрый день.

Подскажите есть в пакете поддержка [кеширования запросов](https://developers.sber.ru/docs/ru/gigachat/api/keeping-context#keshirovanie-zaprosov)?
Почитал код, не увидел - может плохо искал.

Спасибо.

**Comment by TalismanFR** [comment]
Раздел кэширования в документации что-то мимо глаз мне попал. Да, реализую, вещь очень нужная.

**Comment by TalismanFR** [comment]
Реализовано.
